services:
  frontend:
    build: .
    volumes:
      - frontend_dist:/srv/frontend

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - frontend_dist:/srv/frontend
      - caddy_data:/data
      - caddy_config:/config

volumes:
  frontend_dist:
  caddy_data:
  caddy_config: